exclude_files = {
    ".luacheckrc",
    "Libs/",
}

-- https://luacheck.readthedocs.io/en/stable/warnings.html

ignore = {
    "11./BINDING_.*", -- Setting an undefined (Keybinding) global variable
    "211", -- Unused local variable
    "212", -- Unused argument
    "213", -- Unused loop variable
    "432/self", -- Shadowing a local variable
    "542", -- empty if branch
    "631", -- line too long
}

globals = {
    "LiteKeystone",
    "LiteKeystoneDB",
    "LiteKeystoneDungeonButtonMixin",
    "LiteKeystoneDungeonInfoMixin",
    "LiteKeystoneInfo",
    "LiteKeystoneInfoMixin",
    "LiteKeystoneKeyButtonMixin",
    "LiteKeystoneKeyHeaderButtonMixin",
    "LiteKeystoneKeyInfoMixin",
    "LiteKeystoneLogInfoMixin",
    "LiteKeystoneTabButtonMixin",
    "LiteKeystone_AddonCompartmentFunc",
    "SlashCmdList",
}

read_globals = {
    "BLUE_FONT_COLOR",
    "BNGetNumFriends",
    "BNSendGameData",
    "BetterDate",
    "C_BattleNet",
    "C_ChallengeMode",
    "C_ChatInfo",
    "C_Container",
    "C_FriendList",
    "C_MythicPlus",
    "C_Timer",
    "C_WeeklyRewards",
    "ChallengeMode_LoadUI",
    "ChallengesKeystoneFrameAffixMixin",
    "ChatEdit_InsertLink",
    "Clamp",
    "CooldownFrame_Set",
    "CreateFrame",
    "EPIC_PURPLE_COLOR",
    "Enum",
    "EventUtil",
    "FONT_COLOR_CODE_CLOSE",
    "GENERIC_FRACTION_STRING",
    "GREEN_FONT_COLOR",
    "GameTooltip",
    "GameTooltip_Hide",
    "GetClassInfo",
    "GetCurrentRegion",
    "GetDetailedItemLevelInfo",
    "GetFlyoutID",
    "GetFlyoutInfo",
    "GetFlyoutSlotInfo",
    "GetGuildRosterInfo",
    "GetItemInfoFromHyperlink",
    "GetNumFlyouts",
    "GetNumGroupMembers",
    "GetNumGuildMembers",
    "GetRealmName",
    "GetServerTime",
    "GetSpellCooldown",
    "GetSpellDescription",
    "GetSpellInfo",
    "HIGHLIGHT_FONT_COLOR",
    "HybridScrollFrame_CreateButtons",
    "HybridScrollFrame_GetOffset",
    "HybridScrollFrame_Update",
    "IsInGroup",
    "IsInGuild",
    "IsInRaid",
    "IsModifiedClick",
    "Item",
    "LE_PARTY_CATEGORY_HOME",
    "LibStub",
    "LinkUtil",
    "Mixin",
    "ORANGE_FONT_COLOR_CODE",
    "PVP_RATING_CHANGE",
    "RAID_CLASS_COLORS",
    "RATING",
    "RaiderIO",
    "SELECTED_CHAT_FRAME",
    "SendChatMessage",
    "TIMESTAMP_FORMAT_HHMMSS_24HR",
    "UISpecialFrames",
    "UNKNOWN",
    "UnitClass",
    "UnitFactionGroup",
    "UnitFullName",
    "UnitGUID",
    "UnitName",
    "WEEKLY_REWARDS_MYTHIC_TOP_RUNS",
    "WEEKLY_REWARDS_THRESHOLD_MYTHIC",
    "WeeklyRewardExpirationWarningDialog",
    "WeeklyRewardsActivityMixin",
    "WeeklyRewards_LoadUI",
    "YELLOW_FONT_COLOR",
    "format",
    "max",
    "min",
    "mouseButton",
    "string",
    "tContains",
    "table",
    "time",
    "tinsert",
}
